import type { Config } from "tailwindcss";

export default {
  safelist: [
    "flex",
    "flex-col",
    "items-center",
    "text-sm",
    "dark:bg-gray-800flex",
    "w-full",
    "justify-center",
    "gap-1",
    "border-b",
    "border-black/10",
    "bg-gray-50",
    "p-3",
    "text-gray-500",
    "dark:border-gray-900/50",
    "dark:bg-gray-700",
    "dark:text-gray-300group",
    "text-gray-800",
    "dark:text-gray-100",
    "dark:bg-gray-800text-base",
    "gap-4",
    "md:gap-6",
    "md:max-w-2xl",
    "lg:max-w-xl",
    "xl:max-w-3xl",
    "p-4",
    "md:py-6",
    "lg:px-0",
    "m-autow-[30px]",
    "relative",
    "items-endrelative",
    "",
    "rounded-smtext-xs",
    "invisible",
    "absolute",
    "left-0",
    "top-2",
    "-ml-4",
    "-translate-x-full",
    "group-hover:visible",
    "!invisibledark:text-white",
    "disabled:text-gray-300",
    "dark:disabled:text-gray-400h-3",
    "w-3",
    "flex-grow",
    "flex-shrink-0dark:text-white",
    "w-[calc(100%-50px)]",
    "md:gap-3",
    "lg:w-[calc(100%-115px)]flex",
    "gap-3min-h-[20px]",
    "items-start",
    "whitespace-pre-wrap",
    "break-wordstext-gray-400",
    "self-end",
    "lg:self-center",
    "mt-2",
    "gap-2",
    "lg:gap-1",
    "lg:absolute",
    "lg:top-0",
    "lg:translate-x-full",
    "lg:right-0",
    "lg:mt-0",
    "lg:pl-2",
    "visiblep-1",
    "rounded-md",
    "hover:bg-gray-100",
    "hover:text-gray-700",
    "dark:text-gray-400",
    "dark:hover:bg-gray-700",
    "dark:hover:text-gray-200",
    "disabled:dark:hover:text-gray-400",
    "md:invisible",
    "md:group-hover:visibleh-4",
    "w-4",
    "justify-between",
    "lg:blockgroup",
    "dark:bg-[#444654]text-base",
    "h-[30px]",
    "w-[30px]",
    "p-1",
    "rounded-sm",
    "text-white",
    "justify-centerh-6",
    "w-6",
    "text-xs",
    "break-wordsmarkdown",
    "prose",
    "break-words",
    "dark:prose-invert",
    "light",
    "lg:blocktext-gray-400",
    "visibleflex",
    "ml-auto",
    "h-full",
    "disabled:dark:hover:text-gray-400h-4",
    "group",
    "bg-black",
    "mb-4flex",
    "text-gray-200",
    "bg-gray-800",
    "px-4",
    "py-2",
    "font-sans",
    "rounded-t-md",
    "gap-2h-4",
    "overflow-y-auto !whitespace-pre",
    "h-32",
    "md:h-48",
    "flex-shrink-0",
  ],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx,html}",
    "./components/**/*.{js,ts,jsx,tsx,mdx,html}",
    "./app/**/*.{js,ts,jsx,tsx,mdx,html}",
  ],
  darkMode: "media",
  theme: {
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
} satisfies Config;
